# -*- coding: utf-8 -*-
"""ADSN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGtG79BJIETc1KqHh1XNQyW8jAcTVk6Z

# Necessary Libraries (only need to be ran once, it will take approx. 5-10 minutes)
"""

#get files
import gdown
import zipfile
import os

download_folder = "neo_occurrences"

# Create download folder if it doesn't exist
try:
    os.makedirs(download_folder)
except FileExistsError:
    print(f"Download folder '{download_folder}' already exists.")

print("Downloading necessary files...")

# Download the zip file
id_sp = "1eZcCqq5LkzRE0anV-lVPjmIVOxgjq0Up"
output_sp = "tfm_test_lemma.zip"
output_sp_path = f"{download_folder}/{output_sp}"
gdown.download(id=id_sp, output=output_sp_path)

# Download the Excel file
id_cat = "1ZCov-5N8jO2BZDguOFLB_CGVS8orkdKo"
output_cat = "concordances_M_Estruch.xlsx"
output_cat_path = f"{download_folder}/{output_cat}"
gdown.download(id=id_cat, output=output_cat_path)

# Extract the zip file
with zipfile.ZipFile(output_sp_path, 'r') as zip_ref:
    zip_ref.extractall(download_folder)

print("Done!")
